### ISSUE TITLE
XTR Di2: update to 12-speed possible?

### ISSUE THREAD

**Issue by ritzelrocker** [kwakeham/DiHack#3]
Hi Keith & all the others,
Found this great page & I wonder, if it is possible to "upgrade" the 11-speed XTR to 12-speed with this knowledge?
This would be a really great hack  :-)
Thanks a lot & best regards 
Marcus

**Comment by kwakeham** [comment]
The Shimano Private ANT does not affect shifting and shifting compatibility.

**Comment by ritzelrocker** [comment]
OK, Thanks :-)
It's a pity ;-)
